# Generated by Django 5.1.4 on 2024-12-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app00_Reg_Log", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                default="<function now at 0x101416fc0>", verbose_name="data_publish"
            ),
        ),
    ]
