# Generated by Django 5.1.4 on 2024-12-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app00_Reg_Log", "0005_alter_users_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="weapon",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weapon",
            name="src",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
