# Generated by Django 5.1.4 on 2024-12-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app00_Reg_Log", "0007_alter_weapon_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weapon",
            name="src",
            field=models.CharField(max_length=5000),
        ),
    ]
