# Generated by Django 5.1.4 on 2024-12-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app00_Reg_Log", "0008_alter_weapon_src"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="admin_pwd",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
