# Generated by Django 5.1.4 on 2024-12-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app00_Reg_Log", "0009_admin_admin_pwd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="user_name",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="warehouse",
            new_name="warehouse_id",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="statement",
            field=models.CharField(
                blank=True,
                choices=[("已处理", "已处理"), ("未处理", "未处理")],
                max_length=255,
                null=True,
            ),
        ),
    ]
